"""Pull nadir roof tiles for the feature-detection eval (ADR-006 / ADR-002).

Fetches tiles through the SAME production imagery path the pipeline uses
(sidecar.app.imagery.naip.fetch_naip_png -> USDA NAIP via Element84 Earth Search
+ AWS Open Data COGs) so the eval GSD (~30-60 cm) and image characteristics
match what the detector sees at runtime. It reuses that fetcher rather than
opening arbitrary URLs, so the production host allowlist (SSRF defense) applies
unchanged.

It writes PNG tiles to ./imagery/ and records provenance (provider, capture
date, GSD, source) into manifest.json. NAIP is public domain, so the tiles may
be committed; non-redistributable sources would be referenced by manifest only.

Usage:
    cd sidecar
    IMAGERY_LIVE=1 uv run python -m validation.feature_detection.pull_tiles \
        --input validation/feature_detection/tiles_to_pull.yaml

Input YAML: a list of {tile_id, address, bbox: [min_lon,min_lat,max_lon,max_lat],
size_px?}. Without IMAGERY_LIVE a deterministic placeholder PNG is written so the
script is runnable offline (the integrity test relies on committed seed tiles,
not a live pull).
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import date
from pathlib import Path
from typing import Any

import yaml

# Reuse the production NAIP fetcher; do NOT fetch arbitrary URLs here. This keeps
# the eval on the same SSRF-allowlisted imagery host as runtime.
from app.imagery.naip import fetch_naip_png, generate_fixture_png  # noqa: E402

FD_DIR = Path(__file__).resolve().parent
IMAGERY_DIR = FD_DIR / "imagery"
MANIFEST_PATH = FD_DIR / "manifest.json"
DEFAULT_SIZE_PX = 512
DEFAULT_GSD_CM = 60


def _fetch_tile(bbox: list[float], size_px: int) -> bytes:
    """Fetch one tile via the production NAIP path, or a placeholder offline."""
    west, south, east, north = bbox
    if os.environ.get("IMAGERY_LIVE") == "1":
        return fetch_naip_png(west, south, east, north, size_px)
    # Offline / CI: deterministic placeholder so the script runs without network.
    return generate_fixture_png(west, south, east, north, size_px)


def pull(input_path: Path) -> dict[str, Any]:
    """Pull every tile in ``input_path`` and return the manifest dict."""
    spec = yaml.safe_load(input_path.read_text())
    tiles_spec = spec["tiles"] if isinstance(spec, dict) else spec

    IMAGERY_DIR.mkdir(parents=True, exist_ok=True)
    manifest_tiles: list[dict[str, Any]] = []

    for entry in tiles_spec:
        tile_id = entry["tile_id"]
        bbox = entry["bbox"]
        size_px = entry.get("size_px", DEFAULT_SIZE_PX)
        png = _fetch_tile(bbox, size_px)
        rel_path = f"imagery/{tile_id}.png"
        (FD_DIR / rel_path).write_bytes(png)
        manifest_tiles.append(
            {
                "tile_id": tile_id,
                "address": entry.get("address", "unknown"),
                "bbox": bbox,
                "gsd_cm": entry.get("gsd_cm", DEFAULT_GSD_CM),
                "provider": "USDA NAIP",
                "capture_date": entry.get("capture_date", date.today().isoformat()),
                "source_url": "https://earth-search.aws.element84.com/v1/collections/naip",
                "license": "public domain (USDA NAIP)",
                "image_path": rel_path,
            }
        )

    manifest = {
        "_comment": "Generated by pull_tiles.py. NAIP is public domain.",
        "tiles": manifest_tiles,
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Pull NAIP tiles for the feature-detection eval.")
    parser.add_argument("--input", type=Path, required=True, help="YAML list of tiles to pull")
    args = parser.parse_args()
    manifest = pull(args.input)
    print(f"pulled {len(manifest['tiles'])} tile(s) to {IMAGERY_DIR}")


if __name__ == "__main__":
    main()
